'use strict';

/**
 * B-02 and B-03 — THE TWO CHANGES THAT MOVE FINANCIAL RESULTS.
 *
 * Both ship DISABLED. These tests do two jobs:
 *   1. prove the default is unchanged behaviour, bit for bit
 *   2. quantify exactly what activating each one would do, so the decision is
 *      made on numbers rather than on an argument
 *
 * Run with the flags set to see the other side:
 *   VEGA_FORWARD_MODE=matched            node --test tests/materialChanges.test.js
 *   VEGA_IV_IDENTIFIABILITY=relative     node --test tests/materialChanges.test.js
 */

const test = require('node:test');
const assert = require('node:assert/strict');

const bs = require('../src/utils/blackScholes');
const ivm = require('../src/utils/impliedVolatility');

const r = 0.065;

// ===========================================================================
// B-02 — the forward must mature with the option
// ===========================================================================

test('B-02: discountForwardToExpiry carries a future back correctly', () => {
  const S = 24000;
  const Topt = 7 / 365;
  const Tfut = 28 / 365;
  const Ffut = S * Math.exp(r * Tfut);

  const carried = bs.discountForwardToExpiry(Ffut, Tfut, Topt, r);
  const correct = S * Math.exp(r * Topt);
  assert.ok(Math.abs(carried - correct) < 1e-9,
    `carrying the monthly future back must reproduce the weekly forward: ${carried} vs ${correct}`);
});

test('B-02: an exact-maturity future is returned unchanged', () => {
  const T = 28 / 365;
  const F = 24119.97;
  assert.equal(bs.discountForwardToExpiry(F, T, T, r), F);
});

test('B-02: a future settling BEFORE the option is refused, not extrapolated', () => {
  assert.equal(bs.discountForwardToExpiry(24000, 7 / 365, 28 / 365, r), null,
    'extrapolating a forward forwards is not sound — the caller must fall back to carry');
  assert.equal(bs.discountForwardToExpiry(0, 28 / 365, 7 / 365, r), null);
  assert.equal(bs.discountForwardToExpiry(24000, NaN, 7 / 365, r), null);
});

test('B-02: MEASURED impact on delta, IV and vega (weekly index option)', () => {
  const S = 24000;
  const Topt = 7 / 365;
  const Tfut = 28 / 365;
  const Fwrong = S * Math.exp(r * Tfut);   // front-month future — CURRENT behaviour
  const Fright = S * Math.exp(r * Topt);   // maturity-matched   — NEW behaviour
  const sigma = 0.15;

  console.log(`\n  B-02 · WEEKLY NIFTY OPTION, spot ${S}, 7d to expiry, monthly future at 28d`);
  console.log(`  forward CURRENT (monthly fut) = ${Fwrong.toFixed(2)}`);
  console.log(`  forward NEW     (matched)     = ${Fright.toFixed(2)}`);
  console.log(`  error = ${(Fwrong - Fright).toFixed(2)} index points\n`);
  console.log('   STRIKE | TYPE | DELTA now | DELTA new |   diff  | VEGA now | VEGA new');
  console.log('  --------|------|-----------|-----------|---------|----------|---------');

  let maxDeltaShift = 0;
  for (const K of [23600, 23800, 24000, 24200, 24400]) {
    for (const type of ['CE', 'PE']) {
      const now = bs.calculateGreeks76({ F: Fwrong, K, T: Topt, r, sigma, type });
      const nxt = bs.calculateGreeks76({ F: Fright, K, T: Topt, r, sigma, type });
      const d = now.delta - nxt.delta;
      maxDeltaShift = Math.max(maxDeltaShift, Math.abs(d));
      console.log(`   ${String(K).padStart(6)} |  ${type} |   ${now.delta.toFixed(4).padStart(7)} |   ${nxt.delta.toFixed(4).padStart(7)} | ${(d >= 0 ? '+' : '') + d.toFixed(4)} | ${now.vega.toFixed(3).padStart(8)} | ${nxt.vega.toFixed(3).padStart(8)}`);
    }
  }

  console.log(`\n  Max |delta| shift: ${maxDeltaShift.toFixed(4)}`);
  console.log('  The band is [0.05, 0.60]: a shift of this size moves the band');
  console.log('  boundary by roughly one strike, changing WHICH contracts are summed.\n');

  assert.ok(maxDeltaShift > 0.05,
    'the bias must be material enough to justify the change — if this ever drops below ' +
    '0.05 the fix has stopped mattering and the flag can be retired');
  assert.ok(maxDeltaShift < 0.20, 'and bounded — a larger shift would mean something else is wrong');
});

test('B-02: IV solved against the wrong forward is biased', () => {
  const S = 24000;
  const Topt = 7 / 365;
  const Fright = S * Math.exp(r * Topt);
  const Fwrong = S * Math.exp(r * (28 / 365));
  const trueSigma = 0.15;
  const K = 24000;

  // A market price generated by the CORRECT forward...
  const px = bs.theoreticalPrice76({ F: Fright, K, T: Topt, r, sigma: trueSigma, type: 'CE' });
  // ...solved against the WRONG one recovers the wrong volatility.
  const solvedWrong = ivm.impliedVolatility76({ marketPrice: px, F: Fwrong, K, T: Topt, r, type: 'CE' });
  const solvedRight = ivm.impliedVolatility76({ marketPrice: px, F: Fright, K, T: Topt, r, type: 'CE' });

  assert.ok(Math.abs(solvedRight - trueSigma) < 1e-3, 'the matched forward recovers the true IV');
  console.log(`\n  B-02 · IV at ATM: true ${(trueSigma * 100).toFixed(2)}%  ` +
    `matched ${(solvedRight * 100).toFixed(2)}%  front-month ${(solvedWrong * 100).toFixed(2)}%\n`);
  assert.ok(Math.abs(solvedWrong - trueSigma) > 0.005,
    'and the front-month forward does not — this is the IV bias the fix removes');
});

test('B-02: stocks are unaffected (options and futures share monthly expiries)', () => {
  const T = 25 / 365;
  const F = 1400 * Math.exp(r * T);
  // Exact match -> discountForwardToExpiry is a no-op, so both modes agree.
  assert.equal(bs.discountForwardToExpiry(F, T, T, r), F);
});

test('B-02: the default mode is UNCHANGED behaviour', () => {
  const mode = process.env.VEGA_FORWARD_MODE === 'matched' ? 'matched' : 'nearest';
  if (!process.env.VEGA_FORWARD_MODE) {
    assert.equal(mode, 'nearest',
      'shipping default must be the pre-existing behaviour so no stored result moves on deploy');
  }
});

// ===========================================================================
// B-03 — identifiability must scale with the underlying's price
// ===========================================================================

/** Solvable strikes and in-band survivors for one underlying, under one rule. */
function coverage(F, step, tickSize = 0.05) {
  const T = 7 / 365;
  const sigma = 0.30;
  let solvable = 0;
  let inBand = 0;
  for (let i = -20; i <= 20; i++) {
    const K = Number((F + i * step).toFixed(4));
    if (K <= 0) continue;
    const px = bs.theoreticalPrice76({ F, K, T, r, sigma, type: 'CE' });
    const iv = ivm.impliedVolatility76({ marketPrice: px, F, K, T, r, type: 'CE', tickSize });
    if (iv == null) continue;
    solvable += 1;
    const d = Math.abs(bs.calculateGreeks76({ F, K, T, r, sigma, type: 'CE' }).delta);
    if (d >= 0.20 && d <= 0.60) inBand += 1;
  }
  return { solvable, inBand };
}

test('B-03: MEASURED coverage per underlying under the ACTIVE rule', () => {
  const universe = [
    ['NIFTY', 24000, 50],
    ['RELIANCE', 1400, 20],
    ['SBIN', 820, 10],
    ['TATASTEEL', 160, 2.5],
    ['low-priced', 9, 0.5],
  ];

  console.log(`\n  B-03 · identifiability mode = ${ivm.IDENTIFIABILITY_MODE.toUpperCase()}`);
  console.log('   UNDERLYING |     F   | solvable/41 | in 0.20-0.60 band');
  console.log('  ------------|---------|-------------|------------------');
  const results = {};
  for (const [name, F, step] of universe) {
    const c = coverage(F, step);
    results[name] = c;
    console.log(`   ${name.padEnd(10)} | ${String(F).padStart(7)} |       ${String(c.solvable).padStart(2)}/41 |        ${String(c.inBand).padStart(2)}`);
  }
  console.log('');

  assert.equal(results.NIFTY.solvable, 41, 'an index board is fully covered');
});

/**
 * THE CORRECTION.
 *
 * The audit claimed the absolute threshold was removing contracts from the
 * stock Vega sums. It is not. Every strike inside the delta band is solvable on
 * every underlying tested, so the threshold only ever blanks cells that were
 * already outside the band and therefore never contributed to a sum.
 *
 * This test pins the corrected fact so the wrong conclusion cannot be
 * reintroduced from the old audit document.
 */
test('B-03 CORRECTED: the IV threshold removes NO in-band contract', () => {
  const T = 7 / 365;
  const sigma = 0.30;

  console.log('\n  B-03 CORRECTED · does the threshold cost any IN-BAND strike?');
  console.log('   UNDERLYING | in 0.20-0.60 band | ...of which IV-solvable | lost');
  console.log('  ------------|-------------------|-------------------------|------');

  for (const [name, F, step] of [
    ['NIFTY', 24000, 50], ['RELIANCE', 1400, 20],
    ['SBIN', 820, 10], ['TATASTEEL', 160, 2.5],
  ]) {
    let inBand = 0;
    let solvable = 0;
    for (let i = -20; i <= 20; i++) {
      const K = Number((F + i * step).toFixed(4));
      if (K <= 0) continue;
      const d = Math.abs(bs.calculateGreeks76({ F, K, T, r, sigma, type: 'CE' }).delta);
      if (d < 0.20 || d > 0.60) continue;
      inBand += 1;
      const px = bs.theoreticalPrice76({ F, K, T, r, sigma, type: 'CE' });
      if (ivm.impliedVolatility76({ marketPrice: px, F, K, T, r, type: 'CE' }) != null) solvable += 1;
    }
    console.log(`   ${name.padEnd(10)} |        ${String(inBand).padStart(2)}         |           ${String(solvable).padStart(2)}            |   ${inBand - solvable}`);
    assert.equal(solvable, inBand,
      `${name}: the identifiability threshold must not cost an in-band contract`);
  }

  console.log('\n  => The threshold costs ZERO in-band contracts on every underlying.');
  console.log('  => A stock\'s Vega sum uses ~3 contracts because of the STRIKE GRID');
  console.log('     (coarse step relative to a 7-day move), not because of this rule.');
  console.log('  => B-03 is a DISPLAY question, not a Vega-correctness question.\n');
});

test('B-03: the relative rule is price-scale invariant', () => {
  // The mathematical property, stated at the calibrated tolerance.
  const tol = 0.02;
  const relative = (rawVega, tick) => tick / rawVega <= tol;

  // Same moneyness, two price scales. rawVega scales with F.
  assert.equal(relative(1324, 0.05), true, 'ATM index');
  assert.equal(relative(8.8, 0.05), true, 'ATM Rs.160 stock — same standard, both admitted');
  assert.equal(relative(0.5, 0.05), false, 'genuinely unidentifiable is still refused');

  // The absolute rule cannot make that distinction: it is a rupee number applied
  // to a rupee-proportional quantity.
  const absolute = (rawVega) => rawVega >= 2.0;
  assert.equal(absolute(1324), true);
  assert.equal(absolute(8.8), true);
  assert.equal(absolute(1.5), false);
});

test('B-03: the default mode is UNCHANGED behaviour', () => {
  if (!process.env.VEGA_IV_IDENTIFIABILITY) {
    assert.equal(ivm.IDENTIFIABILITY_MODE, 'absolute',
      'shipping default must be the pre-existing rule');
    assert.equal(ivm.isIdentifiable(2.0), true, 'the 2.0 floor is inclusive, as before');
    assert.equal(ivm.isIdentifiable(1.999), false);
    assert.equal(ivm.minTimeValueFor(24000), 0.05, 'flat Rs.0.05 time-value floor, as before');
  }
});
